index:
    path:     /
    defaults: { _controller: VulnBundle:Login:index }

account_show:
    path:     /show/{userId}
    defaults: { _controller: VulnBundle:Account:show }
    requirements:
      userId: \d+

account_new:
    path:     /new/{userId}
    defaults: { _controller: VulnBundle:Account:new }
    requirements:
      userId: \d+

transaction_show_all:
    path:     /show2/
    defaults: { _controller: VulnBundle:Transaction:showAll }
    requirements:
      userId: \d+

transaction_show:
    path:     /show2/{accountId}
    defaults: { _controller: VulnBundle:Transaction:show }
    requirements:
      userId: \d+

user_show:
    path: /user
    defaults: { _controller: VulnBundle:User:show }

user_new:
    path: /user/new
    defaults: { _controller: VulnBundle:User:new }
    requirements:
      userId: \d+