index:
    path:     /
    defaults: { _controller: VulnBundle:Default:index }

login:
    path:     /login
    defaults: { _controller: VulnBundle:Security:login }

account_show:
    path:     /account
    defaults: { _controller: VulnBundle:Account:show }

account_new:
    path:     /account/new
    defaults: { _controller: VulnBundle:Account:new }

transaction_show_all:
    path:     /payment
    defaults: { _controller: VulnBundle:Transaction:showAll }

transaction_show:
    path:     /payment/{accountNumber}
    defaults: { _controller: VulnBundle:Transaction:show }

user_show:
    path: /user
    defaults: { _controller: VulnBundle:User:show }

user_new:
    path: /user/new
    defaults: { _controller: VulnBundle:User:new }
    requirements:
      userId: \d+