# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: ROLE_ADMIN
                    test:
                        password: test
                        roles: ROLE_USER

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        login:
#          pattern: ^/
#          security: false

        secured_area:
            pattern: ^/
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /
#            anonymous: ~
            http_basic: ~

    access_control:
            - { path: ^/login,     roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/,          roles: IS_AUTHENTICATED_FULLY }