<?php

namespace SP\VulnBundle\Entity\Repository;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllAccounts($userId)
    {
        return $this->createQueryBuilder('a')
            ->select('a')
            ->where('a.user = :user_id')
            ->setParameter('user_id', $userId)
            ->getQuery()
            ->getResult();
    }
}
