<?php

namespace SP\VulnBundle\Entity\Repository;

use SP\VulnBundle\Entity\User;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByAccount($accountId)
    {
        return $this->findBy(array(
            'fromAccount' => $accountId
        ));
    }

    public function findByUser(User $user)
    {
        return $this->createQueryBuilder('p')
            ->join('p.fromAccount', 'a')
            ->where('a.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();
    }
}
